### ISSUE TITLE
Internal update of Che

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/che-starter#103]
`Che needs to do any 'internal' update itself, e.g. be able to run Che n+1 on the same PVC as Che n.`

**Comment by ibuziuk** [comment]
@aslakknutsen is it supposed to be done by che-starter ?

**Comment by mlabuda** [comment]
I think this should be configured on OpenShift side, where the Che server is deployed. Che server deployment should have a proper triggers to trigger latest deployment on image change.

**Comment by ibuziuk** [comment]
@aslakknutsen @mlabuda @l0rd So, I guess this is not supposed to be done by che-starter.

**Comment by aslakknutsen** [comment]
@ibuziuk The update of che will currently happen via the Tenant Service from dsaas. But CheHost/Workspace would need to be able to start up on an existing pvc created by an older v of Che. But yes, this is at this point not related to Che Starter

**Comment by ibuziuk** [comment]
@aslakknutsen thanks for clarifications - closing
