### ISSUE TITLE
Live previews are no longer updated on each commit to master

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/che-starter#14]
Master CI job [1]  is now fixed  and image is published to the registry, however changes are not reflected on 

 - http://che-starter.os.ci.centos.org/
 - http://che-starter.demo.almighty.io/

[1] https://ci.centos.org/job/devtools-che-starter-build-master/

**Comment by ibuziuk** [comment]
@kbsingh could you please help to tackle this one ?

**Comment by kbsingh** [comment]
wth the move to the dev registry, I am trying to consolidate all the content to prod-preview cluster, would that do ? if so, lets work that through.

**Comment by kbsingh** [comment]
I just tried a deploy in the new place, and i get : 
```
017-02-24 22:29:38.101 ERROR 1 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Binding to target org.springframework.boot.autoconfigure.web.ServerProperties@d6da883 failed:

    Property: server.port
    Value: tcp://172.30.132.34:32000
    Reason: Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Integer' for property 'port'; nested exception is org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [java.lang.Integer]


Action:

Update your application's configuration
```

**Comment by ibuziuk** [comment]
@kbsingh moving to the new cluster works just fine. In terms of error, I assume that you override application.properties[1] during deployment, so both **server.port** and **server.address** must be used for this. 

[1] https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

**Comment by kbsingh** [comment]
We just render and execute the dockerfile, as far as i can tell.

**Comment by ibuziuk** [comment]
@kbsingh I was able to deploy che-starter app using template from **openshift-template** folder on minishift. The only problem I had was coupled with centos:7 base image - **[Errno 14] HTTP Error 404 - Not Found**:

> Loaded plugins: fastestmirror, ovl
> http://ftp.wcss.pl/pub/linux/centos/7.3.1611/updates/x86_64/repodata/07467f9928e5098492a1115004239b2c17b4178051852fb48394868acbb5b261-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
> Trying other mirror.

However, when I changed base image to centos:6 and push the image[1] to dockerhub there were no problems with deployment. Please, let me know how can I help to tackle this issue. Basically, there were no sufficient changes in comparison with deployment to:

- http://che-starter.os.ci.centos.org/
- http://che-starter.demo.almighty.io/

[1] https://hub.docker.com/r/ibuziuk/che-starter/

**Comment by kbsingh** [comment]
should be fixed now
