### ISSUE TITLE
504 Gateway Time-out when trying to start che-server when it was idled 

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/che-starter#145]
It takes too long to start che-sever if it was idled: 
```
<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
```
`deployCheIfSuspended` [1] is a long-running task
[1] https://github.com/redhat-developer/che-starter/blob/master/src/main/java/io/fabric8/che/starter/openshift/CheDeploymentConfig.java#L41

**Comment by ibuziuk** [comment]
cc: @aslakknutsen @mlabuda @sbryzak

**Comment by mlabuda** [comment]
It took, in my case, 56 seconds to start an idled Che server and  then workspace creation proceeded.

**Comment by ibuziuk** [comment]
PR has been sent - https://github.com/redhat-developer/che-starter/pull/146

**Comment by ibuziuk** [comment]
Should be fixed with https://github.com/redhat-developer/che-starter/pull/146

**Comment by ibuziuk** [comment]
@vpavlin @kbsingh the issue is still reproducible on prod-preview even thought I can not repro it locally when running che-starter via docker ? Is it possible to set connection timeout in template somehow ?

**Comment by ibuziuk** [comment]
The issue is also reproducible locally when che-starter is deployed on minishift (still not reproducible if running che-starter image as docker container)

**Comment by mlabuda** [comment]
I think this will be related to routing on OpenShift. Router/routes have a timeout set for request and it looks like we are hitting those timeouts - that could be a reason why increasing timeout for server on spring boot app side did not help.

**Comment by ibuziuk** [comment]
The problem is that on prod there is no router for che-starter at all and Platform talk with it using internal service IP address which is accessible only inside the cluster
Should be potentially fixed with https://github.com/redhat-developer/che-starter/issues/163

**Comment by ibuziuk** [comment]
Should be fixed once the following UI & wit issues are resolved:
- https://github.com/fabric8-services/fabric8-wit/issues/1506
- https://github.com/fabric8-ui/fabric8-ui/issues/1825

**Comment by ibuziuk** [comment]
This one should be fixed now (UI is asking che server state and starts it asynchronously)
