### ISSUE TITLE
Create a status endpoint for health check

### ISSUE THREAD

**Issue by vpavlin** [redhat-developer/che-starter#150]
Discussed this with @ibuziuk - interim option would be to use `/swagger-ui-html` but as it returns ~3.5KB, it might not be optimal for health checks which are called every couple seconds.

We need an endpoint which will return status 200 if everything is ok and the app is fully started and working and 404 (or other error code) if it is not - this is used also for `readinessProbe` which influences whether the container started properly or not when you do new deployment so it will help us to make sure new deployments actually work.

Please ask should you need more information

**Comment by ibuziuk** [comment]
PR is sent https://github.com/redhat-developer/che-starter/pull/151
The implementation could probably be improved though

**Comment by ibuziuk** [comment]
Closing. @mlabuda @sbryzak guys if you have better ideas for health check please speak up

**Comment by mlabuda** [comment]
https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-monitoring.html#production-ready-health-access-restrictions ?
