### ISSUE TITLE
Clean up loggin

### ISSUE THREAD

**Issue by mlabuda** [redhat-developer/che-starter#177]
Now we have some new structure of logging and it is not easily readable and it does not provide much more useful information. See following example

`2017-05-10 22:18:38.534  INFO 1 --- [cTaskExecutor-2] i.f.che.starter.client.WorkspaceClient   : Polling workspace 'i1elutdi' status...
{"time":"2017-05-10T22:18:38.534+00:00","msg":"Polling workspace 'i1elutdi' status...","logger":"io.fabric8.che.starter.client.WorkspaceClient","thread":"SimpleAsyncTaskExecutor-2","level":"INFO","HOSTNAME":"che-starter-14-1k245"}`

First line provides same necessary information as the second line, except it has better readable format. The JSON for logging output is not good for reading. And another aspect - now we have double amount of logs but it did not raised informative value.

**Comment by mlabuda** [comment]
@ibuziuk why the logging has changed?

**Comment by ibuziuk** [comment]
@mlabuda https://github.com/redhat-developer/che-starter/issues/171 which was requested by platform
