### ISSUE TITLE
Cannot use */oso  endpoints

### ISSUE THREAD

**Issue by mlabuda** [redhat-developer/che-starter#191]
At the moment, e.g. when I want to create a workspace via POST /workspace/oso endpoint, it internally calls keycloak endpoint. This causes */oso endpoint(s) unusable, because it fails.

**Comment by ibuziuk** [comment]
@mlabuda are you sure that */oso endpoints are unusable ? I tested those today against minishift and all worked just fine (keycloak token = null)

**Comment by mlabuda** [comment]
Well, this issue is not valid (anymore? or at all?). I just saw in code, that even though we call workspace/oso endpoint it internally uses GET /stack endpoint with passing keycloak token. But because oso endpoints NOW would work only on Che without Keycloak support, it does not make sense anymore.

Closing as rejected.
