### ISSUE TITLE
Add token.payload['sub'] as identity_id when logging where relevant

### ISSUE THREAD

**Issue by aslakknutsen** [redhat-developer/che-starter#196]
That allows us to track actions of a user across the system. 

The identity_id can be extracted from the Token provided from KC. payload.sub

**Comment by ibuziuk** [comment]
PR is sent - https://github.com/redhat-developer/che-starter/pull/197

**Comment by ibuziuk** [comment]
Merged to master
PR for updating prod - https://github.com/openshiftio/saas/pull/288
