### ISSUE TITLE
Skip importing a project but save it to ws-config

### ISSUE THREAD

**Issue by eivantsov** [redhat-developer/che-starter#214]
This task is related to https://github.com/redhat-developer/rh-che/issues/230

The current mechanism of importing a project is not very reliable - the IDE is being initialized and a project is being imported and there are race conditions. Sometimes, a project is marked as invalid/misconfigured because a project physically exists in a workspace (in `/projects`) but does not exist in workspace config. In fact, when the project is imported using project API, it should update ws-config. That does not always happen.

This commit https://github.com/eclipse/che/commit/a258f2fd11639dd3141c5f9a4d7785cec2cef00d makes it possible to save projects info workspace config, and when a workspace is started it's the IDE that will import the projects:

```
    "projects": [
      {  
           "name":"javaproject",
           "attributes":{  
              "contribute_to_branch":[  
                 "master"
              ]
           },
           "type":"maven",
        "source": {
          "location":"https://github.com/che-samples/console-java-simple.git",
          "type":"git"
        },
           "path":"/javaproject",
           "mixins":[  
              "pullrequest",
               "git"
           ]
}
    ]
```

openshift-connector-wip branch should be updated to have this commit.

**Comment by ibuziuk** [comment]
Closing . Fix has been promoted to prod - https://github.com/openshiftio/saas-openshiftio/pull/173
