### ISSUE TITLE
Readme.md testing with minishift section improvements

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/che-starter#22]
@IlyaBuziuk some comments about the doc:
- Is minishfit v1.0 required? If that is true we should also change the default login/password
- To create the PV we could just reuse the code instructions in rh-che instead of installing gofabric8
- Instructions contains 4 logins and that can be confusing. Maybe addressing my second point would help removing the need for the last login
- If we use che.$(minishift ip).nip.io address we could remove manaul editing of /etc/hosts

**Comment by ibuziuk** [comment]
@l0rd first 3 point are relevant. What is bothering me is the last bullet - I suspect that it is not going to work until https://issues.jboss.org/browse/CHE-145 is resolved, right ? template v1.0.53 still contains "hostname-http" : "che.openshift.mini" in the configMap

**Comment by l0rd** [comment]
@ibuziuk for point 4 we should `oc edit configmap che` and edit hostname-http. 

For gofabric8 my concern is that after `oc apply` che starts and fails because it cannot find the PVs. And `gofabric8 volumes` is not enough: you need to stop the previous Che deployment and create a new one. Ideally we should:
1. Apply the template without starting Che
2. Run `gofabric8 volumes`
3. Start Che
And maybe applying the PVs yaml files is easier

**Comment by ibuziuk** [comment]
@l0rd I need to play with the instructions (ideally I would like to provide a script that will do it in a single step) But what about CHE-145 ? if we apply smth. like that [1] 
CHE_DOCKER_IP_EXTERNAL will be detected automatically and there will be no need for updating configmap, right ? 

[1] https://github.com/ibuziuk/che/commit/1dd23f9d6069a38b15a86217ea1a12543ec5bef0

**Comment by l0rd** [comment]
When CHE-145 will be implemented we won't need modify the config map. But until then we will always need to do that (assuming that https://github.com/fabric8io/fabric8-online/pull/38 will be merged).

**Comment by ibuziuk** [comment]
@l0rd I'm planning to contribute to Che docs the following set of instructions for Minishift deployment - https://github.com/redhat-developer/che-starter/pull/27

Basically, it would be just 3 steps:
1. Install minishift + oc
2. install gofabric8
3. run script 

This scenario works just fine - no need to stop the previous Che deployment and create a new one. WDYT?

**Comment by l0rd** [comment]
LGTM

**Comment by ibuziuk** [comment]
@l0rd @sbryzak actually I jump the gun - the 3 steps scenario does not work fine with the latest 1.0.53 fabric8 template - in order to make it work  an extra step is required: one must either update /etc/hosts and map **minishift ip** to **che.openshift.mini**, or run `oc edit configmap che`, update hostname-http with route and restart che pod (configmap changes does not update deployment automatically - this is also relevant for starting che in debug mode)

So, for now the docs are not ready to be provided to upstream. Should configmapcontroller be added to the template so that configmap changes would update deployment ?

**Comment by l0rd** [comment]
I must confess that I never liked the idea to use a template where configmaps and instructions to deploy Che were together. I would prefer to keep separate config from the application itself.

We may think to use https://github.com/fabric8io/fabric8-online/tree/master/apps/che/src/main/fabric8 instead and:

1. get the configmaps template, edit it and apply it
2. apply the deployment tamplate
3. create route 

First step is needed just once. Then, for every che delete/deploy, configmaps don't need to be redeployed.

**Comment by ibuziuk** [comment]
I think this issue can be closed assuming that up-to-date instructions for fabric8 template deployment are located in rh-che repo and would probably be moved to upstream soon - https://github.com/redhat-developer/rh-che#how-to-run-che-on-openshift

**Comment by l0rd** [comment]
👍
