### ISSUE TITLE
WorkspaceLegacyFormatAdapterTest is not stable 

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/che-starter#269]
Failed tests: 
  WorkspaceLegacyFormatAdapterTest.getWorkspaceLegacyFormat:232 null

More details in https://ci.centos.org/job/devtools-che-starter-prcheck/53/console

**Comment by ScrewTSW** [comment]
@ibuziuk can this issue be closed? did the fix provide stability?

**Comment by ibuziuk** [comment]
@ScrewTSW yeah, let's close it
