### ISSUE TITLE
Remove unused mandatory parameters masterUrl and namespace

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/che-starter#290]
Since we are multi-tenant for quite some time, these two parameters don't make sense anymore AFAIK, but they are still mandatory for requests.
WDYT @ibuziuk ?
Is removing these parameters safe? Or is there some work needed also on codebases-ui side? (wit side?)

**Comment by ibuziuk** [comment]
I would not remove it but rather make it optional. Those might be useful if for some reason che-starter would need to use OpenShift API via kubernetes client
