### ISSUE TITLE
Kubernetes / OpenShift client should be closed after request execution

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/che-starter#30]
@mlabuda feel free to add more details

**Comment by mlabuda** [comment]
From javadoc of okhttp3, which is wrapped in OpenShift client from kubernetes OpenShift client in fabric8
"The threads and connections that are held will be released automatically if they remain idle. But if you are writing a application that needs to aggressively release unused resources you may do so."

the OpenShift client in fabric8 do this stuff in close method. I think it is more safe to close client once it is not required, than relying on having it close on idleness.
