### ISSUE TITLE
Is stopping other workspaces when creating new one really needed?

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/che-starter#312]
Right now, when `POST` to `/workspace` is called, not only new workspace is created, but also all other running workspaces are stopped.
Is this behavior needed?
To my understanding this is not needed because in the OSIO flow, opening workspace already stops other workspaces (calls `PATCH` to `/workspace/{name}`).

I understand, that mostly, this is what users usually do - Create workspace and open it.

Only workflow this is breaking right now is when user is working in one workspace, then goes to OSIO and create another workspace. I would be pretty confused, why creating (not starting!) workspace stops my running workspace.

I'll try to provide PR (should be easy enough) and as this is not very important issue I would like to wait for @ibuziuk to come back from PTO to review.

**Comment by ibuziuk** [comment]
stopping all workspaces during creation used to be necessary, but since codebase ui has been changed and create & start call are stopping all workspaces during create execution is not needed anymore

**Comment by ibuziuk** [comment]
PR is merged - https://github.com/redhat-developer/che-starter/pull/313
