### ISSUE TITLE
Provide a way for "fail safe"

### ISSUE THREAD

**Issue by mlabuda** [redhat-developer/che-starter#34]
E.g. when we receive a call in Che starter and we create a resource/resources on OpenShift, we should be able to perform clean up if something go really wrong and the desired state is not achieved. E.g. workspace start-up fail, we should be able to perform clean up on such "broken" resources. Basically calls should/could behave like transactions = either call is performed whole and successful, or we "fail safe back" as it has never happened.

**Comment by ibuziuk** [comment]
Che starter does not use kubernetes / openshift API anymore and play the role of API adapter. Closing since this issue is deprecated.
