### ISSUE TITLE
Che starter creates a wrong workspace 

### ISSUE THREAD

**Issue by mlabuda** [redhat-developer/che-starter#48]
I uses swagger output for CURL to create a workspace:
`curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: EmHPEus9-BTL6DMfvy9mdmlhG2WahNW1ezKFe8Eo6pA' -d '{ "branch": "master", "description": "https://github.com/mlabuda/vertx-with-che#master", "id": "aaasdsad",  "name": "dasdasdaasdas",  "repo": "https://github.com/mlabuda/vertx-with-che.git", "stack": "vert.x" }' 'http://localhost:10000/workspace/oso?masterUrl=https%3A%2F%2F192.168.99.100%3A8443%2F&namespace=eclipse-che'` 

Try to replace masterURL and Authorization header token by your values and see what happens. It should create a stack on vert.x centos image, but it creates it on eclipse ubuntu jdk8 image.

**Comment by ibuziuk** [comment]
Fixed in https://github.com/redhat-developer/che-starter/pull/49
