### ISSUE TITLE
che-starter needs to pass the keycloak authentication token that it receives from platform to che server with every request

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/che-starter#51]
Expected header:
`Authorization: Bearer <KEYCLOAK_TOKEN>`

**Comment by ibuziuk** [comment]
Done for Stack controller - https://github.com/redhat-developer/che-starter/pull/58

**Comment by mlabuda** [comment]
This has been done also for /workspace endpoints. Can we close this one?

**Comment by ibuziuk** [comment]
@mlabuda I believe it is not fully implemented - need to add KeycloakInterceptor to every RestTemplate

**Comment by mlabuda** [comment]
you are rights. We should check all requests to Che server/Che workspace endpoints to be intercepted by the keycloak.

**Comment by ibuziuk** [comment]
should be fixed now. Closing
