### ISSUE TITLE
Do we need to update memmory limits for workspace creation ?

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/che-starter#56]
See https://github.com/redhat-developer/che-starter/blob/master/src/main/resources/templates/workspace_template.json#L12

cc. @amisevsk @l0rd 

This might be fixed on fabric8 template side

**Comment by ibuziuk** [comment]
@amisevsk @l0rd I guess the answer here would be NO, right ? (done via fabric8 template [1] env vars) 

[1] https://github.com/fabric8io/fabric8-online/blob/master/apps/che/src/main/fabric8/deployment.yml

**Comment by amisevsk** [comment]
@ibuziuk I think we're good. We're currently assigning limits in the file you linked; workspace limit is set by `CHE_OPENSHIFT_WORKSPACE_MEMORY_OVERRIDE`, and server limit is assigned directly.

**Comment by ibuziuk** [comment]
@amisevsk ok, closing as won't fix in this case ;-)

**Comment by ibuziuk** [comment]
@mlabuda do you think this issue might be coupled with https://github.com/redhat-developer/che-starter/issues/128 and we do need to set memory limits on che-starter side ?

**Comment by mlabuda** [comment]
Well, question is how is the Che server deployed. Whether a che.openshift.workspace.memory.override property is set properly and server uses it. Otherwise it uses data passed in a request. And in that case it would create oversized containers. 

If we change it on Che starter side, we are safe no matter what the Che server uses (if it does not use wrong values set through property :) ).

**Comment by ibuziuk** [comment]
@mlabuda ok, so to be on a safe side we should also set it while workspace creation - https://github.com/fabric8io/fabric8-online/blob/master/apps/che/src/main/fabric8/cm.yml#L13

**Comment by mlabuda** [comment]
Yeah, when getting a workspace config (from GET /stack and filtering), we should update the memory constraint from default 2 GB to 1300 MB. And pass such updated config to Che server.
