### ISSUE TITLE
Need to reduce che-starter image size

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/che-starter#57]
From email thread "che-starter size"

> KB:
> The che-starter built image is over 0.5GB in size. It takes 20 times
> longer to deploy than the entire core api (13 seconds V/s 0.8 )
> What options do we have here to try and address this ?
> Pavol:
> do we need JDK for running it, isn't JRE enough? You can decrease image size by ~100MB by not installing JDK and cleaning Yum cache.

JDK is now required because of the certificate installation ( `javac` [1] is involved)

[1] https://github.com/redhat-developer/che-starter/blob/master/Dockerfile#L21

**Comment by ibuziuk** [comment]
@kbsingh Am I correct that this issue is not a priority for summit. The image size is **475.7 MB** and I do not see how it can be reduced

**Comment by kbsingh** [comment]
not a priority for now.

**Comment by ibuziuk** [comment]
Closing as won't fix. Feel free to reopen if it will be needed
