### ISSUE TITLE
Commands are not available after workspace creation 

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/che-starter#66]
Need to add Stacks commands to workspace creation 

[1] https://github.com/eclipse/che/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json#L127

**Comment by mlabuda** [comment]
Well, for now we are using a simple json template to create a workspace. To do it more robust, we could use output from get /stack API call - create a look up on returned collection based on an ID of a stack and use the json of stack, from the returned API response JSON array, as a template for WS creation.

**Comment by ibuziuk** [comment]
@mlabuda would you like to work on this issue ?

**Comment by ibuziuk** [comment]
I was thinking about creating API `getCommands(String stackID)` and injecting it directly to template

**Comment by mlabuda** [comment]
Yeah, injecting command would be another thing, but it would increase complexity of starter (another necessary call to create a new workspace - then it reduces maximum "bandwidth" = amount of calls for che-starter. I will work on this one

**Comment by ibuziuk** [comment]
@mlabuda yeah, I agree. It was decided to stick to template approach for summit, but if we can improve it now and provide enough tests to cover this API - why not. However, it seems that commands & projectType (https://github.com/redhat-developer/che-starter/issues/70 ) are the only missing pieces
