### ISSUE TITLE
Model the workspace creation request using DTOs instead of a template

### ISSUE THREAD

**Issue by sbryzak** [redhat-developer/che-starter#69]
This will allow for more flexibility and future-proofing.

**Comment by ibuziuk** [comment]
@sbryzak could you clarify why do we need two types of DTO - Workspace & WorspaceTemplate ? Also some of the classes are empty like WorkspaceServer / WorkspaceProject - is it WIP ?

**Comment by ibuziuk** [comment]
it was decided to put this new DTO approach for later (after summit) and now stick to old json template approach

**Comment by ibuziuk** [comment]
@mlabuda I guess this is done now and workspace template file can be safely removed, right ?

**Comment by mlabuda** [comment]
Yeah, we can safely remove workspace template file from resources. I forgot on that one when was cleaning template classes.

**Comment by ibuziuk** [comment]
@mlabuda could you please remove and we can close this issue ?

**Comment by ibuziuk** [comment]
@mlabuda yeah, I agree - https://github.com/redhat-developer/che-starter/issues/78 
Just need to be sure that nothing will be broken ;-)
