### ISSUE TITLE
Need to create a mapping between Stack ID and project Type

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/che-starter#70]
For now all projects are created with 'maven' projectType [1]. Need to create a mapping between Stack Id and project Type e.g. **"node-default"** -> **"node-js"**

All project types are defined in https://github.com/eclipse/che/blob/master/ide/che-core-ide-templates/src/main/resources/samples.json

[1] https://github.com/redhat-developer/che-starter/blob/master/src/main/resources/templates/project_template.json#L3

**Comment by mlabuda** [comment]
For this issue I would suggest more robust solution. We should have an agreement how the stacks we provide in our Che distribution are tailored - either a mandatory Tags, Components... We should have a contract for this.

Then we have to somehow decide, what kind of project is the one passed through che-starter. We should discuss this further on mtg.

**Comment by ibuziuk** [comment]
@mlabuda project type should be explicitly set on project creation step - the only way to figure it out is having mapping between stackId & project type.

Note: project type is not a part of the stack definition.

[1] https://github.com/redhat-developer/che-starter/blob/master/src/main/java/io/fabric8/che/starter/client/StackClient.java#L71
[2]  https://github.com/redhat-developer/che-starter/blob/master/src/main/java/io/fabric8/che/starter/model/StackProjectMapping.java#L25

**Comment by mlabuda** [comment]
Yeah, I am aware of that. If we would assume that to create a project we always obtain a git remote, we could somehow decide it based on repo, but it would be overkill. 

With components, tag I had in mind, that a single project can be imported into various workspaces (java maven project could be in default-java, vert-x...). And a single workspace can have various projects (blank, maven, java). So there is M:N mapping. And decision based on workspace configuration would help too.

One more problem could be, if we are trying to create a project in workspace which would have set a specific projectType, but the project itself does not have this nature. E.g. we would be creating a project with maven project type but it wouldnt have to posses pom.xml necessary.

**Comment by ibuziuk** [comment]
@mlabuda well, this kind of solution is not ideal, but IMO the most suitable for summit purposes where there will be only a few stacks supported. Note, this issue was created because of the red X on the projects with invalid project type  - https://issues.jboss.org/browse/CHE-133
So, technically *"blank"* type can be set and this will work just fine for our scenario. 
IMO, we should not over engineering project type picking, because it simply does not worth it. There are other more important issue we still need to tackle ;-)

**Comment by mlabuda** [comment]
Ok, I agree, there are more important issues to address :) So basically we should go with "blank" for any project - it is safer than assuming a project type is maven and it would not have pom.xml at all in project repo.

**Comment by ibuziuk** [comment]
@mlabuda hmmm.. not sure because for demo I think maven project is going to be used. So, I would opt for approach with mapping that we are controlling and assumption that all vertx project imported are going to be maven based

**Comment by mlabuda** [comment]
For the demo it works, but once users will start using it, it could broke there.

**Comment by ibuziuk** [comment]
During the meeting it was decided to stick with the mapping (stack ID -> projectType) approach for now
