### ISSUE TITLE
Create tests for most of API endpoints.

### ISSUE THREAD

**Issue by mlabuda** [redhat-developer/che-starter#79]

**Comment by ibuziuk** [comment]
@mlabuda Do we have a plan for test coverage ? Would be great to figure out what needs to be done in terms of tests by the sprint planning

**Comment by mlabuda** [comment]
I think we should cover all API endpoints - GET stacks, POST and GET workspace. Server is not yet implemented so this can be done later.

**Comment by ibuziuk** [comment]
@mlabuda are we going to run tests for endpoints against https://github.com/redhat-developer/che-vertx-server ? If yes, are there plans to deploy it on some cluster

**Comment by ibuziuk** [comment]
BTW, I have created issue for server API - https://github.com/redhat-developer/che-starter/issues/85
Would be great if we could also implement this (but not a priority IMO)

**Comment by mlabuda** [comment]
This has been done. We can close this one.
