### ISSUE TITLE
We should provide workspace IDE URL on workspace creation

### ISSUE THREAD

**Issue by mlabuda** [redhat-developer/che-starter#81]

**Comment by ibuziuk** [comment]
cc: @aslakknutsen 

We have removed workspace template and now Platform will not be able to call `getIDEWorkspaceUrl` to get the link. Will it be ok if che-starter return only URL to the workspace instead of the whole Workspace Object?

**Comment by aslakknutsen** [comment]
```
POST /workspace

201 Created
Location: IDEWorkspaceUrl
```

is fine by me..

**Comment by ibuziuk** [comment]
@aslakknutsen I found DTO for workspace links that would be really handy to use:
```
{
  "href": "http://che.192.168.42.126.nip.io/che/zkren1m2",
  "rel": "ide url",
  "method": "GET"
}
```

**Comment by ibuziuk** [comment]
Fixed - https://github.com/redhat-developer/che-starter/pull/82
