### ISSUE TITLE
Reevaluate and refactor WorkspaceCreateParams

### ISSUE THREAD

**Issue by mlabuda** [redhat-developer/che-starter#95]

**Comment by ibuziuk** [comment]
@mlabuda is it for summit ?

**Comment by mlabuda** [comment]
well, we could have more accurate API. At the moment, there is an ID in the workspace create param, which is basically ID of a project, not a workspace and thus it is ambigous. It could be projectId. Then we have a description, which is useless because we dont use it from request, but we construct it, so we can remove this from workspace param.
